### ISSUE TITLE
About page link redirects to organisations page

### ISSUE THREAD

**Issue by Jeremy-Prior** [kartoza/SAEOSS-Portal#128]
If a user clicks on the `About` link in the nav bar they get redirected to the organisation page

[issue126_1.webm](https://github.com/kartoza/SAEOSS-Portal/assets/100694811/4e94764e-7837-4f99-9f0e-eede2102829b)

**Comment by EliVolsch** [comment]
The about page content has not been created yet it seems. This page should be created and implemented

The content of the about page should provide the following at minimum: 

- Provide some background on the project  (purpose and mission)
- Display release notes
- Link to partners websites

**Comment by zamuzakki** [comment]
We can create default pages which include about page using
` docker exec -ti saeoss_ckan-web_1 poetry run ckan saeoss bootstrap create-pages`

I have created About page on staging: http://10.150.16.178:5000/pages
To edit the content, click the About page listing then click Edit. 

The About menu on staging is not yet linked to About page, since it needs my PR to be deployed first.

**Comment by Indiphile** [comment]
`About`  menu items redirects  to the correct page.
