### ISSUE TITLE
Test STAC endpoint

### ISSUE THREAD

**Issue by voogt** [kartoza/SAEOSS-Portal#205]
Test STAC endpoint in pycsw with data harvested from web portal
- [ ] STAC endpoint returns data from portal that was harvested through STAC endpoint

**Comment by zamuzakki** [comment]
I have tested the PyCSW endpoints, and **the harvested dataset are not returned by the endpoint**
The reason is: Only datasets having tags will be added to PyCSW collections.
So, I'll make another ticket to add default tag called "general". This way, the harvested datasets will be added to PyCSW by default
