### ISSUE TITLE
Update the scheming plugin

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/SAEOSS-Portal#24]
Change poetry and pyproject.toml, handle multiple pages validation errors with the new scheming plugin

**Comment by Mohab25** [comment]
@Fanevanjanahary after changing the poetry and pyproject files and have the new plugin version, currently working on the scheming validation which now causes errors after clicking next, see the screenshot below (notice there are three pages now instead of two )



![Screenshot from 2023-05-02 09-54-58](https://user-images.githubusercontent.com/58084234/235601322-5ac03e5e-8a6b-434f-a2e0-15110e8c4df5.png)

**Comment by EliVolsch** [comment]
@Fanevanjanahary  can we close this as resolved?
